when@dev:
  _errors:
    resource: "@FrameworkBundle/Resources/config/routing/errors.xml"
    prefix: /error
register:
  path: /register
  controller: App\Controller\RegistrationController::register


